apiVersion: v1
kind: Service
metadata:
  name: pokero-app
spec:
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: pokero-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokero-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: pokero-app
  template:
    metadata:
      labels:
        app: pokero-app
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - "python manage.py collectstatic --noinput && gunicorn --timeout 120 -b 0.0.0.0:8000 app.wsgi:application"
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: PRODUCTION
              value: {{ .Values.app.env.production | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.app.env.postgres_host }}
            - name: POSTGRES_PORT
              value: {{ .Values.app.env.postgres_port | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.app.env.postgres_user }}
            - name: POSTGRES_DB
              value: {{ .Values.app.env.postgres_db }}
            - name: POSTGRES_PASSWORD_FILE
              value: /etc/secrets/db_password
            - name: SECRET_KEY_FILE
              value: /etc/secrets/secret_key
            - name: ALLOWED_HOSTS
              value: "*" 
          volumeMounts:
            - name: secrets
              mountPath: /etc/secrets
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
            - name: static-volume
              mountPath: /backend/app/staticfiles
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets | first | pluck "name" | first }}
      volumes:
        - name: secrets
          secret:
            secretName: pokero-secrets
        - name: tmp-volume
          emptyDir: {}
        - name: static-volume
          emptyDir: {}
