apiVersion: v1
kind: Service
metadata:
  name: pokero-app
spec:
  type: ClusterIP 
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: pokero-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokero-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: pokero-app
  template:
    metadata:
      labels:
        app: pokero-app
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests: 
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }} 
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
          command:
            - "/bin/sh"
            - "-c"
            - "python manage.py collectstatic --noinput && gunicorn --timeout 120 -b 0.0.0.0:8000 app.wsgi:application"
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: PRODUCTION
              value: {{ .Values.app.env.production | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.app.env.postgres_host }}
            - name: POSTGRES_PORT
              value: {{ .Values.app.env.postgres_port | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.app.env.postgres_user }}
            - name: POSTGRES_DB
              value: {{ .Values.app.env.postgres_db }}
            # Wskazujemy na pliki w zamontowanym wolumenie
            - name: POSTGRES_PASSWORD_FILE
              value: /etc/secrets/db_password
            - name: SECRET_KEY_FILE
              value: /etc/secrets/secret_key
            # Automatyczne ALLOWED_HOSTS (pobiera IP poda, ale dodajemy * dla LB)
            - name: ALLOWED_HOSTS
              value: "*" 
          # Montujemy sekret jako pliki
          volumeMounts:
            - name: secrets
              mountPath: /etc/secrets
              readOnly: true
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets | first | pluck "name" | first }}
      volumes:
        - name: secrets
          secret:
            secretName: pokero-secrets
