{{- if .Values.networkPolicy.enabled -}}

# 1. DEFAULT DENY
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
# 2. DNS 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-dns
spec:
  podSelector: {} 
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

---
# 3. INGRESS -> APP
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-ingress
spec:
  podSelector:
    matchLabels:
      app: pokero-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
    ports:
    - protocol: TCP
      port: 8000

---
# 4. APP -> DB
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-app-to-db
spec:
  podSelector:
    matchLabels:
      app: pokero-app
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          cluster-name: pokero-db-cluster 
    ports:
    - protocol: TCP
      port: 5432

# 5. Policy for DB cluster (Zalando/Spilo)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-db-cluster-policy
spec:
  podSelector:
    matchLabels:
      cluster-name: pokero-db-cluster 
  policyTypes:
  - Ingress
  - Egress

  ingress:
  # A. Django app
  - from:
    - podSelector:
        matchLabels:
          app: pokero-app
    ports:
    - protocol: TCP
      port: 5432

  # Master talk to replica
  - from:
    - podSelector:
        matchLabels:
          cluster-name: pokero-db-cluster
    ports:
    - protocol: TCP
      port: 5432 
    - protocol: TCP
      port: 8008 

  # C. Operator 
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgres-operator
    ports:
    - protocol: TCP
      port: 8008 # Patroni API
    - protocol: TCP
      port: 5432

  # D. Monitoring
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.monitoringNamespace }}

  egress:
  - to:
    - podSelector:
        matchLabels:
          cluster-name: pokero-db-cluster
    ports:
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 8008

  # B. Do K8S API 
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 443

---
# 6. MONITORING 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-monitoring
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.monitoringNamespace }}
    ports:
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 9100
    - protocol: TCP
      port: 5432
{{- end }}
