{{- if .Values.networkPolicy.enabled -}}

# 1. Default Deny
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
# 2. DNS 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-dns
spec:
  podSelector:
    matchLabels:
      app: pokero-app
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

---
# 3. INGRESS -> APP 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-ingress
spec:
  podSelector:
    matchLabels:
      app: pokero-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 8000 }}

---
# 4. APP -> DB 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-app-to-db
spec:
  podSelector:
    matchLabels:
      app: pokero-app
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: pokero-db
    ports:
    - protocol: TCP
      port: 5432

---
# 5. DB <- APP (ingress to db)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-db-allow-app
spec:
  podSelector:
    matchLabels:
      app: pokero-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: pokero-app
    ports:
    - protocol: TCP
      port: 5432

---
# 6. MONITORING 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-monitoring
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.monitoringNamespace }}
    ports:
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 9100
    - protocol: TCP
      port: 5432
{{- end }}
