apiVersion: v1
kind: Secret
metadata:
  name: pokero-secrets
type: Opaque
stringData:
  # Te nazwy kluczy staną się nazwami plików w /run/secrets/
  db_password: {{ .Values.secrets.db_password | quote }}
  secret_key: {{ .Values.secrets.secret_key | quote }}
