# Image
image:
  repository: ghcr.io/kompocikdot/pokero
  tag: d141aac9e0e0a9302a1e8e29447e8711044b2c25 
  pullPolicy: Always

# App
app:
  replicas: 1
  port: 8000
  env:
    production: "true"
    postgres_host: "pokero-db" 
    postgres_port: "5432"
    postgres_user: "pokero"
    postgres_db: "pokero"

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# Secrets 
secrets: {}

db:
  image: postgres:18-alpine
  storageSize: 1Gi

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"


imagePullSecrets:
  - name: ghcr-secret



autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

