# Image
image:
  repository: ghcr.io/kompocikdot/pokero
  tag: latest
  pullPolicy: Always

# App
app:
  replicas: 1
  port: 8000
  env:
    production: "true"
    postgres_host: "pokero-db" 
    postgres_port: "5432"
    postgres_user: "pokero"
    postgres_db: "pokero"

# Secrets 
secrets: {}

db:
  image: postgres:18-alpine
  storageSize: 1Gi


imagePullSecrets:
  - name: ghcr-secret


resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

